# Generated by Django 5.0.9 on 2024-11-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('master', 'master'), ('user', 'user')], default='user', max_length=9),
        ),
    ]
