# Generated by Django 5.0.9 on 2024-11-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_is_staff_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='имя оператора', max_length=30, verbose_name='имя сотрудника'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='фамилия оператора', max_length=30, verbose_name='фамилия сотрудника'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operator', 'Operator'), ('master', 'Master'), ('admin', 'Administrator')], default='operator', max_length=9, verbose_name='должность'),
        ),
    ]
