services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000  # Запуск сервера Django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      PG_DATABASE: mytestdb
      PG_USER: userone
      PG_PASSWORD: password
      PG_HOST: db
      PG_PORT: 5432

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: mytestdb
      POSTGRES_USER: userone  # Убедитесь, что это совпадает с настройками Django
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

