# Generated by Django 5.0.9 on 2024-11-15 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shift_assignment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(default='Наименование операции:', max_length=255)),
                ('detail_name', models.CharField(max_length=100, verbose_name='Наименование изделия')),
                ('machine_id', models.IntegerField(default=1, verbose_name='ID станка')),
                ('parameter_name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detail_quantity', models.IntegerField(default=0, verbose_name='Количество деталей')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Отметка о выполнении задания')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shift_assignment.shiftassignment', verbose_name='Cменное задание')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'process_history',
                'verbose_name_plural': 'process_histories',
            },
        ),
    ]
