# Generated by Django 5.0.9 on 2024-12-30 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shift_assignment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=255, verbose_name='Наименование операции:')),
                ('detail_name', models.CharField(max_length=100, verbose_name='Наименование изделия')),
                ('part_id', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('machine_id', models.IntegerField(default=1, verbose_name='№ станка')),
                ('parameter_name', models.CharField(max_length=100, verbose_name='Параметры')),
                ('value', models.CharField(max_length=100, verbose_name='Значение специальной характеристики')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detail_quantity', models.IntegerField(default=0, verbose_name='Количество деталей')),
                ('mark_yes_no', models.BooleanField(default=True, verbose_name='Отметка да/нет')),
                ('control_code', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('3;2', '3;2')], default=1, max_length=10, verbose_name='Код контроля')),
                ('roughness_check', models.CharField(choices=[('+', '+'), ('-', '-')], default='+', max_length=1, verbose_name='Шероховатость')),
                ('defects_check', models.CharField(choices=[('+', '+'), ('-', '-')], default='+', max_length=1, verbose_name='Отсутствие рисок, канавок и т.д.')),
                ('threading_check', models.CharField(choices=[('+', '+'), ('-', '-')], default='+', max_length=1, verbose_name='Наличие резьбы и отверстия под шплинт')),
                ('diameter_check', models.CharField(choices=[('+', '+'), ('-', '-')], default='+', max_length=1, verbose_name='Диаметр галтели')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Завершено')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shift_assignment.shiftassignment', verbose_name='Сменное задание')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'process_history',
                'verbose_name_plural': 'process_histories',
            },
        ),
    ]
