# Generated by Django 5.0.9 on 2024-11-15 11:52

import django.contrib.auth.mixins
import django.db.models.deletion
import django.views.generic.base
import django.views.generic.edit
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(default='Процесс ...', max_length=255)),
                ('detail_name', models.CharField(max_length=100, verbose_name='Наименование изделия')),
                ('machine_id', models.IntegerField(default=1, verbose_name='ID станка')),
                ('parameter_name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detail_quantity', models.IntegerField(default=0, verbose_name='Количество деталей')),
            ],
            options={
                'verbose_name': 'process_history',
                'verbose_name_plural': 'process_histories',
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(default='Не указано', max_length=100, verbose_name='Операция')),
                ('machine_id', models.CharField(max_length=50, verbose_name='№ станка')),
                ('part_id', models.CharField(max_length=50, verbose_name='Наименование детали')),
                ('batch_number', models.CharField(max_length=50, verbose_name='Номер партии')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'shift_assignment',
                'verbose_name_plural': 'shift_assignments',
            },
        ),
        migrations.CreateModel(
            name='CompleteProcessHistoryView',
            fields=[
                ('processhistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='process_history.processhistory')),
            ],
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, 'process_history.processhistory', django.views.generic.base.TemplateView),
        ),
        migrations.CreateModel(
            name='HistoryProcessCreateView',
            fields=[
                ('processhistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='process_history.processhistory')),
            ],
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, 'process_history.processhistory', django.views.generic.edit.FormView),
        ),
    ]
