# Generated by Django 5.0.9 on 2024-11-08 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processhistory',
            options={'verbose_name': 'process history', 'verbose_name_plural': 'process histories'},
        ),
        migrations.AddField(
            model_name='processhistory',
            name='detail_name',
            field=models.CharField(default='default_value', max_length=100, verbose_name='Наименование изделия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processhistory',
            name='detail_quantity',
            field=models.IntegerField(default=0, verbose_name='Количество деталей'),
        ),
        migrations.AlterField(
            model_name='processhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
