# Generated by Django 5.0.9 on 2025-01-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processhistory',
            name='detail_name',
        ),
        migrations.RemoveField(
            model_name='processhistory',
            name='parameter_name',
        ),
    ]
