# Generated by Django 5.0.9 on 2024-11-09 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_history', '0002_alter_processhistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата задания')),
                ('machine_id', models.CharField(max_length=50, verbose_name='ID машины')),
                ('part_id', models.CharField(max_length=50, verbose_name='ID детали')),
                ('batch_number', models.CharField(max_length=50, verbose_name='Номер партии')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Сменное задание',
                'verbose_name_plural': 'Сменные задания',
            },
        ),
    ]
