# Generated by Django 5.0.9 on 2024-11-15 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_history', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processhistory',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='process_history.shiftassignment', verbose_name='Cменное задание'),
        ),
        migrations.DeleteModel(
            name='HistoryProcessCreateView',
        ),
    ]
