# Generated by Django 5.0.9 on 2024-12-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_history', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
