# Generated by Django 5.0.9 on 2024-12-27 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_history', '0003_delete_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='processhistory',
            name='machine_id',
            field=models.IntegerField(default=1, verbose_name='№ станка'),
        ),
        migrations.AlterField(
            model_name='processhistory',
            name='process_name',
            field=models.CharField(max_length=255, verbose_name='Наименование операции:'),
        ),
        migrations.AlterField(
            model_name='processhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='оператор'),
        ),
    ]
