# Generated by Django 5.0.9 on 2024-11-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_history', '0004_processhistory_is_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processhistory',
            name='process_name',
            field=models.CharField(default='Наименование операции:', max_length=255),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='operation_name',
            field=models.CharField(max_length=100, verbose_name='Операция'),
        ),
    ]
