# Generated by Django 5.0.9 on 2024-12-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_history', '0004_alter_processhistory_machine_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processhistory',
            name='parameter_name',
            field=models.CharField(max_length=100, verbose_name='Параметры'),
        ),
        migrations.AlterField(
            model_name='processhistory',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Значение специальной характеристики'),
        ),
    ]
