# Generated by Django 5.0.9 on 2024-11-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_history', '0004_processhistory_machine_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftassignment',
            name='date',
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='operation_name',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Операция'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='machine_id',
            field=models.CharField(max_length=50, verbose_name='№ станка'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='part_id',
            field=models.CharField(max_length=50, verbose_name='Наименование детали'),
        ),
    ]
