# Generated by Django 5.0.9 on 2024-12-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_history', '0005_alter_processhistory_parameter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processhistory',
            name='control_code',
            field=models.CharField(choices=[('1', 'Код 1'), ('2', 'Код 2'), ('3', 'Код 3'), ('4', 'Код 4'), ('5', 'Код 5'), ('6', 'Код 6'), ('3;2', 'Код 3;2')], default='1', max_length=10, verbose_name='Код контроля'),
        ),
    ]
