# Generated by Django 5.0.9 on 2024-11-14 05:26

import django.contrib.auth.mixins
import django.db.models.deletion
import django.views.generic.base
import django.views.generic.edit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_history', '0005_remove_shiftassignment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteProcessHistoryView',
            fields=[
                ('processhistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='process_history.processhistory')),
            ],
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, 'process_history.processhistory', django.views.generic.base.TemplateView),
        ),
        migrations.CreateModel(
            name='HistoryProcessCreateView',
            fields=[
                ('processhistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='process_history.processhistory')),
            ],
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, 'process_history.processhistory', django.views.generic.edit.FormView),
        ),
    ]
