# Generated by Django 5.0.9 on 2024-12-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_history', '0010_alter_processhistory_control_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processhistory',
            name='control_code',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('3;2', '3;2')], default=1, max_length=10, verbose_name='Код контроля'),
        ),
    ]
