# Generated by Django 5.0.9 on 2024-12-30 22:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=255)),
                ('machine_id', models.CharField(max_length=50)),
                ('part_id', models.CharField(max_length=50)),
                ('batch_number', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('defect_quantity', models.IntegerField(blank=True, null=True)),
                ('stop_reason', models.TextField(blank=True, null=True)),
                ('operator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shift_assignment_completedshiftassignment',
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=100, verbose_name='Операция')),
                ('machine_id', models.CharField(max_length=50, verbose_name='№ станка')),
                ('part_id', models.CharField(default='', max_length=50, verbose_name='Наименование детали')),
                ('batch_number', models.CharField(default='', max_length=50, verbose_name='Номер партии')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'shift_assignment',
                'verbose_name_plural': 'shift_assignment',
            },
        ),
    ]
