# Generated by Django 5.0.9 on 2024-11-18 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftassignment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
