# Generated by Django 5.0.9 on 2025-01-01 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedshiftassignment',
            options={'verbose_name': 'Завершенное задание', 'verbose_name_plural': 'Завершенные задания'},
        ),
        migrations.AlterModelOptions(
            name='shiftassignment',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AddField(
            model_name='completedshiftassignment',
            name='shift_assignment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='completed_assignments', to='shift_assignment.shiftassignment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completedshiftassignment',
            name='defect_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='completedshiftassignment',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
