# Generated by Django 5.0.9 on 2024-12-26 10:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0002_remove_shiftassignment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftassignment',
            name='master_id',
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='batch_number',
            field=models.CharField(max_length=50, verbose_name='Номер партии'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='machine_id',
            field=models.CharField(max_length=50, verbose_name='№ станка'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='operation_name',
            field=models.CharField(max_length=100, verbose_name='Операция'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='part_id',
            field=models.CharField(max_length=50, verbose_name='Наименование детали'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
