# Generated by Django 5.0.9 on 2025-01-03 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0002_alter_completedshiftassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedshiftassignment',
            name='batch_number',
            field=models.CharField(max_length=50, verbose_name='№ партии'),
        ),
        migrations.AlterField(
            model_name='completedshiftassignment',
            name='machine_id',
            field=models.CharField(max_length=50, verbose_name='№ станка'),
        ),
        migrations.AlterField(
            model_name='completedshiftassignment',
            name='operation_name',
            field=models.CharField(max_length=255, verbose_name='Наименование операции'),
        ),
        migrations.AlterField(
            model_name='completedshiftassignment',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='completedshiftassignment',
            name='part_id',
            field=models.CharField(max_length=50, verbose_name='Наименование продукции'),
        ),
        migrations.AlterField(
            model_name='completedshiftassignment',
            name='stop_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причины остановки'),
        ),
    ]
