# Generated by Django 5.0.9 on 2024-11-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0002_remove_shiftassignment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftassignment',
            name='master',
        ),
    ]
