# Generated by Django 5.0.9 on 2024-11-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0003_remove_shiftassignment_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
