# Generated by Django 5.0.9 on 2025-01-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0005_alter_completedshiftassignment_stop_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedshiftassignment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
