# Generated by Django 5.0.9 on 2025-01-04 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0007_remove_completedshiftassignment_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedshiftassignment',
            name='status',
        ),
    ]
