# Generated by Django 5.0.9 on 2025-01-07 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0008_remove_completedshiftassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedshiftassignment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
