# Generated by Django 5.0.9 on 2025-01-09 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0009_completedshiftassignment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedshiftassignment',
            name='shift_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_assignments', to='shift_assignment.shiftassignment'),
        ),
    ]
