# Generated by Django 5.0.9 on 2025-01-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0010_alter_completedshiftassignment_shift_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedshiftassignment',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
