# Generated by Django 5.0.9 on 2025-01-12 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0011_alter_completedshiftassignment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedshiftassignment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
